version: "3.8"

services:
  service-discovery:
    build: ./ServiceDiscovery
    ports:
      - "3000:3000"
    networks:
      - shop-management-network
  api-gateway:
    build: ./APIGateway
    ports:
      - "3001:3001"
    networks:
      - shop-management-network
  staff-service:
    build: ./StaffsService
    ports:
      - "8080:8080"
    networks:
      - shop-management-network
  customer-service:
    build: ./CustomersService
    ports:
      - "8081:8081"
    networks:
      - shop-management-network
  product-service:
    build: ./ProductService
    ports:
      - "8082:8082"
    networks:
      - shop-management-network
  purchase-service:
    build: ./PurchaseService
    ports:
      - "8083:8083"
    networks:
      - shop-management-network
  analysis-service:
    build: ./AnalysisService
    ports:
      - "8084:8084"
    networks:
      - shop-management-network



networks:
    shop-management-network:
        driver: bridge