eureka:
  client:
    service-url:
        defaultZone: http://localhost:3000/eureka/
    register-with-eureka: true
    fetch-registry: true
    instance:
      hostname: localhost

spring:
  application:
    name: API_GATEWAY
  cloud:
    gateway:
      routes:
        - id: AuthService
          uri: lb://AuthService
          predicates:
            - Path=/auth/**
          filters:
            - AuthenticationFilter

        - id: CustomersService
          uri: lb://CustomersService
          predicates:
            - Path=/api/v1/customers/**
          filters:
            - AuthenticationFilter

        - id: StaffsService
          uri: lb://StaffsService
          predicates:
            - Path=/api/v1/staff/**
          filters:
            - AuthenticationFilter

        - id: ProductService
          uri: lb://ProductService
          predicates:
            - Path=/api/v1/products/**
          filters:
            - AuthenticationFilter

        - id: PurchaseService
          uri: lb://PurchaseService
          predicates:
            - Path=/api/v1/purchase/**
          filters:
            - AuthenticationFilter

        - id: AnalyticsService
          uri: lb://AnalyticsService
          predicates:
            - Path=/api/v1/analytics/**
          filters:
            - AuthenticationFilter